#!/usr/bin/env node
// Generate native TouchDesigner GLSL adapters directly from the browser's
// canonical optical/material formulas. No browser, wrapper, or video texture.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import * as source from '../viz/src/nebula-shaders.js';
import { CORE_LENS_FRAGMENT } from '../viz/src/core-lensing-shaders.js';
import { CORE_RAY } from '../viz/src/core-ray.js';

const output=new URL('./shaders/',import.meta.url);
const pipeline=await readFile(new URL('../viz/src/artwork-pipeline.js',import.meta.url),'utf8');
const spaceSource=await readFile(new URL('../viz/src/nebula-space.js',import.meta.url),'utf8');
const check=process.argv.includes('--check');
const files=new Map();
const camera=/* glsl */`
// One perspective Camera COMP drives these and the Render TOP camera.
uniform vec4 uCameraPos, uCameraRight, uCameraUp, uCameraForward;
uniform vec4 uCameraInfo; // tan(vertical FOV/2), aspect, near, far
uniform vec4 uViewport;   // physical width, height, inverse width, inverse height
vec3 tdWorldToView(vec3 p) {
  vec3 q=p-uCameraPos.xyz;
  return vec3(dot(q,uCameraRight.xyz),dot(q,uCameraUp.xyz),-dot(q,uCameraForward.xyz));
}
vec3 tdViewToWorld(vec3 p) {
  return uCameraPos.xyz+uCameraRight.xyz*p.x+uCameraUp.xyz*p.y-uCameraForward.xyz*p.z;
}
mat3 tdViewBasis() {
  return transpose(mat3(uCameraRight.xyz,uCameraUp.xyz,-uCameraForward.xyz));
}
// OpenGL [-1,1] clip Z is used only to encode a portable near=0/far=1
// color-depth texture; MAT rasterization always uses TDWorldToProj().
vec4 tdPerspectiveClip(vec3 world) {
  vec3 p=tdWorldToView(world);
  float n=uCameraInfo.z,f=uCameraInfo.w,t=uCameraInfo.x;
  return vec4(p.x/(t*uCameraInfo.y),p.y/t,
    -(f+n)/(f-n)*p.z-2.0*f*n/(f-n),-p.z);
}
`;
const pixelScale=/* glsl */`
float nebulaPixelScale(vec3 viewPosition) {
  return 0.5*uViewport.y/uCameraInfo.x/max(0.0001,-viewPosition.z);
}
`;
const fetches=(samplers)=>samplers.map(name=>`uniform sampler2D ${name};`).join('\n')+/* glsl */`
uniform float uCount;
vec4 instanceTexel(sampler2D image,int index) {
  int width=textureSize(image,0).x;
  return texelFetch(image,ivec2(index%width,index/width),0);
}
`;
function replaceOnce(text,from,to) {
  if(!text.includes(from)||text.indexOf(from)!==text.lastIndexOf(from))throw new Error(`Adapter source contract changed: ${String(from).slice(0,110)}`);
  return text.replace(from,to);
}
function put(name,body,sourceText=body) {
  const hash=createHash('sha256').update(sourceText).digest('hex').slice(0,16);
  files.set(name,`// Generated by touchdesigner/generate-shaders.mjs; source ${hash}.\n// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.\n${body.replace(/[ \t]+$/gm, '').trim()}\n`);
}
function matVertex(text,{kind}) {
  let shader=text.replace(/^\s*attribute [^;]+;[^\n]*$/gm,'').replace(/\bvarying\b/g,'out');
  shader=shader.replace(source.NEBULA_PIXEL_SCALE,pixelScale);
  shader=shader.replaceAll('modelViewMatrix*vec4(p,1.0)','vec4(tdWorldToView(p),1.0)');
  shader=shader.replaceAll('mat3(modelViewMatrix)','tdViewBasis()');
  let load='';
  let samplers;
  if(kind==='filament') {
    samplers=['sStarts','sEnds','sData','sMotion'];
    load=`vec3 aStart=instanceTexel(sStarts,id).xyz;\nvec3 aEnd=instanceTexel(sEnds,id).xyz;\nvec4 aData=instanceTexel(sData,id);\nvec4 aMotion=instanceTexel(sMotion,id);\nvec3 position=vec3(P.x+0.5,P.y*2.0,0.0);`;
    shader=shader.replaceAll('(modelViewMatrix*vec4(nebulaTransform(aStart),1.0)).xyz','tdWorldToView(nebulaTransform(aStart))');
    shader=shader.replaceAll('(modelViewMatrix*vec4(nebulaTransform(aEnd),1.0)).xyz','tdWorldToView(nebulaTransform(aEnd))');
    shader=replaceOnce(shader,'gl_Position=projectionMatrix*vec4(p,1.0);','gl_Position=TDWorldToProj(vec4(tdViewToWorld(p),1.0));');
  } else {
    samplers=['sPositions','sData','sSizes','sMotion'];
    load=`vec3 ${kind==='dust'?'position':'aCenter'}=instanceTexel(sPositions,id).xyz;\nvec4 aData=instanceTexel(sData,id);\nvec2 aSize=instanceTexel(sSizes,id).xy;\nvec4 aMotion=instanceTexel(sMotion,id);`;
    if(kind==='dust') {
      shader='out vec2 vSpriteUv;\n'+shader;
      shader=replaceOnce(shader,'gl_Position = projectionMatrix*viewPosition;','vSpriteUv=vec2(P.x+0.5,0.5-P.y);');
      shader=replaceOnce(shader,'gl_PointSize = rasterSize;',`viewPosition.xy+=P.xy*rasterSize/max(nebulaPixelScale(viewPosition.xyz),0.0001);\n    gl_Position=TDWorldToProj(vec4(tdViewToWorld(viewPosition.xyz),1.0));`);
    } else {
      load+='\nvec3 position=P;\nvec2 uv=P.xy+0.5;';
      shader=replaceOnce(shader,'gl_Position=projectionMatrix*viewPosition;','gl_Position=TDWorldToProj(vec4(tdViewToWorld(viewPosition.xyz),1.0));');
    }
  }
  shader=replaceOnce(shader,'void main() {',`void main() {\n    int id=TDInstanceID();\n    if(id>=int(uCount)) { gl_Position=vec4(2.0,2.0,2.0,1.0);return; }\n    ${load}`);
  return camera+'\n'+fetches(samplers)+'\n'+shader;
}
function matPixel(text,{sprite=false}={}) {
  let shader=text.replace(/precision highp float;/g,'').replace(/\bvarying\b/g,'in');
  if(sprite)shader='in vec2 vSpriteUv;\n'+shader.replaceAll('gl_PointCoord','vSpriteUv');
  // The second native Render TOP writes sparse normalized depth into color.
  // Its MAT is unblended with depth testing/writing enabled; clear to white.
  shader=shader.replace(/gl_FragColor\s*=\s*vec4\(0\.0\);\s*return;/g,'gl_FragColor=vec4(vec3(gl_FragCoord.z),1.0); return;');
  shader=shader.replace(/gl_FragColor\s*=\s*([^;]+);/g,'fragColor=TDOutputSwizzle($1);');
  return 'layout(location=0) out vec4 fragColor;\n'+shader;
}
put('dust.vert',matVertex(source.DUST_VERTEX,{kind:'dust'}),source.DUST_VERTEX);
put('dust.frag',matPixel(source.DUST_FRAGMENT,{sprite:true}),source.DUST_FRAGMENT);
put('atmosphere.vert',matVertex(source.ATMOSPHERE_VERTEX,{kind:'atmosphere'}),source.ATMOSPHERE_VERTEX);
put('atmosphere.frag',matPixel(source.ATMOSPHERE_FRAGMENT),source.ATMOSPHERE_FRAGMENT);
put('filament.vert',matVertex(source.FILAMENT_VERTEX,{kind:'filament'}),source.FILAMENT_VERTEX);
put('filament.frag',matPixel(source.FILAMENT_FRAGMENT),source.FILAMENT_FRAGMENT);

function spaceShader(name) {
  const found=spaceSource.match(new RegExp(`const ${name}=\\/\\* glsl \\*\\/ \\x60([\\s\\S]*?)\\x60;`));
  if(!found)throw new Error(`Decorative space shader ${name} contract changed`);
  return found[1];
}
const starVertex=spaceShader('STAR_VERTEX');
let stars=starVertex.replace(/^\s*attribute [^;]+;[^\n]*$/gm,'').replace(/\bvarying\b/g,'out')
  .replace('uniform float uViewportHeight;','out vec2 vSpriteUv;');
stars=replaceOnce(stars,'void main() {',`void main() {
    int id=TDInstanceID();
    if(id>=int(uCount)){gl_Position=vec4(2.0,2.0,2.0,1.0);return;}
    vec3 position=instanceTexel(sPositions,id).xyz;
    vec3 aColor=instanceTexel(sColors,id).rgb;
    vec2 aSize=instanceTexel(sSizes,id).xy;
    vSpriteUv=vec2(P.x+0.5,0.5-P.y);`);
stars=replaceOnce(stars,'vec4 view=modelViewMatrix*vec4(position,1.0);','vec4 view=vec4(tdWorldToView(position),1.0);');
stars=replaceOnce(stars,'gl_Position=projectionMatrix*view;','');
stars=replaceOnce(stars,'float scale=0.5*uViewportHeight*projectionMatrix[1][1];','float scale=0.5*uViewport.y/uCameraInfo.x;');
stars=replaceOnce(stars,'if(projectionMatrix[3][3]<0.5)scale/=max(0.001,-view.z);','scale/=max(0.001,-view.z);');
stars=replaceOnce(stars,'gl_PointSize=clamp(diameter,1.2,8.0);',`float pointSize=clamp(diameter,1.2,8.0);
    view.xy+=P.xy*pointSize/scale;
    gl_Position=TDWorldToProj(vec4(tdViewToWorld(view.xyz),1.0));`);
stars=stars.replaceAll('gl_PointSize','pointSize');
put('stars.vert',camera+'\n'+fetches(['sPositions','sColors','sSizes'])+'\n'+stars,starVertex);
put('stars.frag',matPixel(spaceShader('STAR_FRAGMENT'),{sprite:true}),spaceShader('STAR_FRAGMENT'));
const cloudVertex=spaceShader('CLOUD_VERTEX');
let clouds=cloudVertex.replace(/^\s*attribute [^;]+;[^\n]*$/gm,'').replace(/\bvarying\b/g,'out');
clouds=replaceOnce(clouds,'void main() {',`void main() {
    int id=TDInstanceID();
    if(id>=int(uCount)){gl_Position=vec4(2.0,2.0,2.0,1.0);return;}
    vec3 aCenter=instanceTexel(sPositions,id).xyz;
    float aSize=instanceTexel(sSizes,id).x;
    float aSeed=instanceTexel(sData,id).x;
    vec3 position=P;vec2 uv=P.xy+0.5;`);
clouds=replaceOnce(clouds,'vec4 view=modelViewMatrix*vec4(aCenter,1.0);','vec4 view=vec4(tdWorldToView(aCenter),1.0);');
clouds=replaceOnce(clouds,'gl_Position=projectionMatrix*view;','gl_Position=TDWorldToProj(vec4(tdViewToWorld(view.xyz),1.0));');
put('clouds.vert',camera+'\n'+fetches(['sPositions','sSizes','sData'])+'\n'+clouds,cloudVertex);
put('clouds.frag',matPixel(spaceShader('CLOUD_FRAGMENT')),spaceShader('CLOUD_FRAGMENT'));

let core=CORE_LENS_FRAGMENT.replace('precision highp float;','').replace('in vec2 vRayNdc;','')
  .replace('out vec4 fragColor;','layout(location=0) out vec4 fragColor;\nlayout(location=1) out vec4 fragDepth;')
  .replace('uniform mat4 uInverseProjection, uCameraWorld, uWorldToDisk, uDiskToClip;','')
  .replace('uniform float uPerspective, uPixelCone, uActive;','uniform float uActive;');
core=replaceOnce(core,'vec4 clip=uDiskToClip*vec4(p,1.0);','vec4 clip=tdPerspectiveClip(nebulaTransform(p));');
const cameraStart=core.indexOf('    vec4 nearView=');
const cameraEnd=core.indexOf('    vec2 interval=sphere(',cameraStart);
if(cameraStart<0||cameraEnd<0)throw new Error('Core camera source contract changed');
core=core.slice(0,cameraStart)+/* glsl */`
    vec2 vRayNdc=vUV.st*2.0-1.0;
    vec3 worldOrigin=uCameraPos.xyz;
    vec3 worldDirection=normalize(uCameraForward.xyz+uCameraRight.xyz*vRayNdc.x*uCameraInfo.x*uCameraInfo.y+uCameraUp.xyz*vRayNdc.y*uCameraInfo.x);
    vec3 origin=nebulaInverse(worldOrigin);
    vec3 direction=normalize(nebulaInverse(worldDirection));
    float uPerspective=1.0;
    float uPixelCone=2.0*uCameraInfo.x/uViewport.y;
`+core.slice(cameraEnd);
core=replaceOnce(core,'void main() {',`void main() {\n    fragColor=TDOutputSwizzle(vec4(0.0));\n    fragDepth=TDOutputSwizzle(vec4(1.0));`);
core=core.replaceAll('discard;','return;');
core=replaceOnce(core,'fragColor=vec4(light,alpha);','fragColor=TDOutputSwizzle(vec4(light,alpha));');
core=replaceOnce(core,'gl_FragDepth=firstDepth;','fragDepth=TDOutputSwizzle(vec4(vec3(firstDepth),1.0));');
const inverse=/* glsl */`
vec3 nebulaInverse(vec3 p) {
  mat3 basis=mat3(nebulaTransform(vec3(1,0,0)),nebulaTransform(vec3(0,1,0)),nebulaTransform(vec3(0,0,1)));
  return transpose(basis)*p;
}
`;
put('core.frag',camera+'\n'+source.NEBULA_TRANSFORM+'\n'+inverse+'\n'+core,CORE_LENS_FRAGMENT);

function pipelineShader(name) {
  const found=pipeline.match(new RegExp(`const ${name} = material\\(\x60([\\s\\S]*?)\x60, \\{`));
  if(!found)throw new Error(`Pipeline shader ${name} contract changed`);
  return found[1];
}
function top(text) {
  return ('layout(location=0) out vec4 fragColor;\n#define vUv vUV.st\n'+text)
    .replace(/precision highp float;/g,'').replace(/varying vec2 vUv;/g,'')
    .replace(/\btexture2D\b/g,'texture').replace(/gl_FragColor\s*=\s*([^;]+);/g,'fragColor=TDOutputSwizzle($1);');
}
const lensSource=pipelineShader('lens');
let lens=top(lensSource).replace('uniform sampler2D uField, uDepth, uCore, uCoreDepth;',`#define uField sTD2DInputs[0]\n#define uDepth sTD2DInputs[1]\n#define uCore sTD2DInputs[2]\n#define uCoreDepth sTD2DInputs[3]`)
  .replace('uniform vec2 uCenter, uClip;','').replace('uniform float uRadius, uAspect, uDistance, uEnabled;','');
// Browser depth textures use NearestFilter. GLSL TOP's linear input filtering
// must remain available for color, so enforce nearest/clamp-to-edge here.
const depthReads=/texture\((uDepth|uCoreDepth),([^)]*)\)\.r/g;
if([...lens.matchAll(depthReads)].length!==4)throw new Error('Composite depth sampling source contract changed');
lens=lens.replace(depthReads,'depthTexel($1,$2)');
lens=/* glsl */`
float depthTexel(sampler2D image,vec2 uv) {
  ivec2 size=textureSize(image,0);
  ivec2 coord=clamp(ivec2(floor(uv*vec2(size))),ivec2(0),size-ivec2(1));
  return texelFetch(image,coord,0).r;
}
`+lens;
// The helper distanceAt() needs the camera clip range outside main().
lens=lens.replaceAll('uClip.x','uCameraInfo.z').replaceAll('uClip.y','uCameraInfo.w');
lens=replaceOnce(lens,'void main() {',`void main() {
      vec3 coreView=tdWorldToView(vec3(0.0));
      float uDistance=-coreView.z,uAspect=uCameraInfo.y;
      float uEnabled=uDistance>${CORE_RAY.horizon.toFixed(8)}?1.0:0.0;
      vec2 uCenter=vec2(0.5);
      float uRadius=0.0;
      if(uEnabled>0.5) {
        uCenter+=coreView.xy/vec2(uCameraInfo.x*uAspect,uCameraInfo.x)/uDistance*0.5;
        uRadius=0.5*${CORE_RAY.horizon.toFixed(8)}/uCameraInfo.x/sqrt(max(0.00000001,uDistance*uDistance-${(CORE_RAY.horizon**2).toFixed(12)}));
      }`);
put('composite.frag',camera+'\n'+lens,lensSource);
const extract=pipelineShader('extract');
put('bloom-extract.frag',top(extract).replace('uniform sampler2D uImage;','#define uImage sTD2DInputs[0]'),extract);
const blur=pipelineShader('blur');
put('bloom-blur.frag',top(blur).replace('uniform sampler2D uImage; uniform vec2 uStep;','#define uImage sTD2DInputs[0]\nuniform vec4 uBlurStep;\n#define uStep uBlurStep.xy'),blur);
const finish=pipelineShader('finish');
put('finish.frag',top(finish).replace('uniform sampler2D uImage; uniform sampler2D uGlow;','#define uImage sTD2DInputs[0]\n#define uGlow sTD2DInputs[1]'),finish);

const contract={
  version:1,target:'TouchDesigner 2023.12230; native GLSL MAT/TOP, parameter glslversion=glsl430 (native probe verified)',
  geometry:'Rectangle SOP on XY, P.x/y -0.5..0.5; identity Geometry COMP; native instancing enabled with exact count and no per-instance transform channels',
  textures:'RGBA32F, nearest, no mipmaps; linear texel id=(row*width+column); all samplers of one draw share dimensions; unused texels zero',
  camera:{uCameraPos:'world position xyz',uCameraRight:'unit world right xyz',uCameraUp:'unit world up xyz',uCameraForward:'unit world forward into scene xyz',uCameraInfo:['tan(verticalFovRadians/2)','width/height','near','far'],uViewport:['physicalWidth','physicalHeight','1/width','1/height']},
  shared:{uTime:'recorded milliseconds',uDuration:'recorded duration milliseconds >=1',uOrbit:'radians',uTilt:'radians added to 40-degree artwork inclination',uAnimation:'seconds',uActivity:'0..1',uMotionSpeed:'0..1',uMotionTurn:'-1..1',uMotionCoherence:'0..1',uSelLane:'-1 or selected lane',uHoverLane:'-1 or hovered lane',uReplaying:'0 or 1',uPointMax:'physical pixels, browser default128',uPointScale:'retained compatibility uniform; perspective uses camera+viewport',uAtmosphere:'0 for dust',uDepthPass:'0 color; 1 sparse depth',uCount:'exact instance count',uActive:'1 core enabled'},
  mats:{
    dust:{vertex:'dust.vert',pixel:'dust.frag',samplers:{sPositions:'localXYZ,0',sData:'timeMs,lane,noteOn,heat',sSizes:'worldDiameter,radiance,0,0',sMotion:'speed,turn,tangentDirection,radialDirection'}},
    atmosphere:{vertex:'atmosphere.vert',pixel:'atmosphere.frag',samplers:{sPositions:'localXYZ,0',sData:'timeMs,lane,noteOn,heat',sSizes:'worldDiameter,radiance,0,0',sMotion:'speed,turn,tangentDirection,radialDirection'}},
    filament:{vertex:'filament.vert',pixel:'filament.frag',samplers:{sStarts:'local start XYZ,0',sEnds:'local end XYZ,0',sData:'endTimeMs,lane,heat,XYdisplacement',sMotion:'speed,turn,tangentDirection,radialDirection'}},
    stars:{vertex:'stars.vert',pixel:'stars.frag',recordedData:false,samplers:{sPositions:'world XYZ,0',sColors:'linear RGB,0',sSizes:'worldDiameter,radiance,0,0'}},
    clouds:{vertex:'clouds.vert',pixel:'clouds.frag',recordedData:false,samplers:{sPositions:'world XYZ,0',sSizes:'worldDiameter,0,0,0',sData:'seed,0,0,0'}},
  },
  rendering:{color:'RGBA16F or RGBA32F Render TOP, transparent black clear, MAT RGB blend Source Alpha + One, postmultalpha=False, depth-test on, depth-write off',depth:'second native RGBA32F Render TOP of dust/filaments/stars only; clone MAT uDepthPass=1, blend off, depth-test/write on, opaque white clear; output R is normalized window depth',core:'core.frag GLSL TOP, RGBA32F, numcolorbufs=2; buffer0 linear premultiplied emission RGBA, buffer1 normalized depth R (far1 on no hit); wire core to Render Select TOP and set index=1 (2023 native parameter)',composite:'inputs [fieldColor,fieldDepth,coreColor,coreDepth] in this order; native perspective camera must match the vector uniforms; leave inputfiltertype linear for color, depth uses shader-enforced nearest texelFetch with clamp-to-edge matching browser depth textures',bloom:'bloom-extract input composite, half resolution; bloom-blur horizontal then vertical for spread1.0 and2.4: uBlurStep=(spread/W,0,0,0) or(0,spread/H,0,0)',finish:'inputs [composite,finalBlur]; exact browser exposure1.18, bloom0.21, linear-to-sRGB and grain0.003; no additional output color transform'},
  docs:['https://docs.derivative.ca/Write_a_GLSL_MAT','https://docs.derivative.ca/Write_a_GLSL_TOP','https://docs.derivative.ca/Render_Select_TOP'],
};
files.set('contract.json',JSON.stringify(contract,null,2)+'\n');

// Fail regeneration when upstream contracts change, rather than silently
// shipping unresolved Three.js identifiers into native TouchDesigner.
for(const [name,body]of files)if(/\.(vert|frag)$/.test(name)) {
  for(const forbidden of [/\battribute\b/,/\bvarying\b/,/\bmodelViewMatrix\b/,/\bprojectionMatrix\b/,/\bgl_PointCoord\b/,/\bgl_FragColor\b/,/\buInverseProjection\b/,/\buDiskToClip\b/]) {
    if(forbidden.test(body))throw new Error(`${name}: unresolved source token ${forbidden}`);
  }
  if((body.match(/\{/g)||[]).length!==(body.match(/\}/g)||[]).length)throw new Error(`${name}: unbalanced braces`);
  if(!body.includes('void main()'))throw new Error(`${name}: missing main`);
}
await mkdir(output,{recursive:true});
let changed=0;
for(const [name,body]of files) {
  const path=new URL(name,output);
  const existing=await readFile(path,'utf8').catch(()=>null);
  if(existing===body)continue;
  changed++;
  if(check)console.error(`Out of date: ${fileURLToPath(path)}`);
  else await writeFile(path,body);
}
if(check&&changed)process.exitCode=1;
else console.log(`${check?'Verified':'Generated'} ${files.size} native TouchDesigner shader/contract files (${changed} changed).`);
