// Generated by touchdesigner/cinematic/generate-field.mjs; source 7d910ec4a1499100.
// Native GLSL 4.30; exact source geometry/time with layered HDR optics.
// One perspective Camera COMP drives these and the Render TOP camera.
uniform vec4 uCameraPos, uCameraRight, uCameraUp, uCameraForward;
uniform vec4 uCameraInfo; // tan(vertical FOV/2), aspect, near, far
uniform vec4 uViewport;   // physical width, height, inverse width, inverse height
vec3 tdWorldToView(vec3 p) {
  vec3 q=p-uCameraPos.xyz;
  return vec3(dot(q,uCameraRight.xyz),dot(q,uCameraUp.xyz),-dot(q,uCameraForward.xyz));
}
vec3 tdViewToWorld(vec3 p) {
  return uCameraPos.xyz+uCameraRight.xyz*p.x+uCameraUp.xyz*p.y-uCameraForward.xyz*p.z;
}
mat3 tdViewBasis() {
  return transpose(mat3(uCameraRight.xyz,uCameraUp.xyz,-uCameraForward.xyz));
}
// OpenGL [-1,1] clip Z is used only to encode a portable near=0/far=1
// color-depth texture; MAT rasterization always uses TDWorldToProj().
vec4 tdPerspectiveClip(vec3 world) {
  vec3 p=tdWorldToView(world);
  float n=uCameraInfo.z,f=uCameraInfo.w,t=uCameraInfo.x;
  return vec4(p.x/(t*uCameraInfo.y),p.y/t,
    -(f+n)/(f-n)*p.z-2.0*f*n/(f-n),-p.z);
}

uniform sampler2D sPositions;
uniform sampler2D sData;
uniform sampler2D sSizes;
uniform sampler2D sMotion;
uniform float uCount;
vec4 instanceTexel(sampler2D image,int index) {
  int width=textureSize(image,0).x;
  return texelFetch(image,ivec2(index%width,index/width),0);
}





  uniform float uSelLane;
  uniform float uSolo;
  uniform float uHoverLane;
  out vec2 vUv;
  out vec3 vColor;
  out float vAlpha;
  out vec3 vVolumePosition;
  out vec3 vVolumeRay;
  out float vFootprint;
  out vec2 vMotion;

  uniform float uTime;
  uniform float uDuration;
  uniform float uOrbit;
  uniform float uTilt;
  vec3 nebulaTransform(vec3 p) {
    float angle = uOrbit + 3.45575191895 * uTime / max(uDuration, 1.0);
    float c = cos(angle), s = sin(angle);
    p.xy = mat2(c, s, -s, c) * p.xy;
    float inclination = 0.6981317008 + uTilt;
    c = cos(inclination); s = sin(inclination);
    p.yz = mat2(c, s, -s, c) * p.yz;
    c = 0.9689124217; s = -0.2474039593;
    p.xy = mat2(c, s, -s, c) * p.xy;
    return p;
  }
  vec3 nebulaLight(float heat) {
    vec3 cold = vec3(0.115, 0.39, 0.64);
    vec3 ice = vec3(0.47, 0.72, 0.86);
    vec3 amber = vec3(1.0, 0.39, 0.105);
    float warmth=smoothstep(0.63,0.9,heat);
    return mix(mix(cold,ice,smoothstep(0.18,0.63,heat)),amber,warmth)*(1.0+warmth*0.25);
  }

  out float vViewDepth;

void main() {
    int id=TDInstanceID();
    if(id>=int(uCount)) { gl_Position=vec4(2.0,2.0,2.0,1.0);return; }
    vec3 aCenter=instanceTexel(sPositions,id).xyz;
vec4 aData=instanceTexel(sData,id);
vec2 aSize=instanceTexel(sSizes,id).xy;
vec4 aMotion=instanceTexel(sMotion,id);
vec3 position=P;
vec2 uv=P.xy+0.5;
    vec3 p=nebulaTransform(aCenter);
    vec4 viewPosition=vec4(tdWorldToView(p),1.0);
    vec3 radial=normalize(vec3(aCenter.xy,0.0));
    vec3 movement=vec3(-radial.y,radial.x,0.0)*aMotion.z+radial*aMotion.w;
    vec3 direction=tdViewBasis()*nebulaTransform(movement);
    float angle=length(direction.xy)>0.000001 ? atan(direction.y,direction.x) : 0.0;
    float c=cos(angle),s=sin(angle);
    vec2 offset=mat2(c,s,-s,c)*(position.xy*vec2(1.0+aMotion.x*0.55,1.0-aMotion.x*0.22))*aSize.x;
    viewPosition.xy+=offset;
    mat3 basis=tdViewBasis()*mat3(nebulaTransform(vec3(1,0,0)),nebulaTransform(vec3(0,1,0)),nebulaTransform(vec3(0,0,1)));
    // Dot products transpose the rotation without requiring GLSL inverse().
    vVolumePosition=aCenter+vec3(dot(basis[0].xy,offset),dot(basis[1].xy,offset),dot(basis[2].xy,offset));
    vVolumeRay=vec3(basis[0].z,basis[1].z,basis[2].z);
    vFootprint=aSize.x;
    vMotion=aMotion.xy;
    vViewDepth=-viewPosition.z;
    gl_Position=TDWorldToProj(vec4(tdViewToWorld(viewPosition.xyz),1.0));
    float focus=1.0-step(0.5,abs(aData.y-uSelLane));
    float hover=(1.0-step(0.5,abs(aData.y-uHoverLane)))*0.5;
    float isolation=uSelLane < -0.5 ? 1.0 : mix(uSolo > 0.5 ? 0.0 : 0.15, 2.3, focus);
    vAlpha=aSize.y*step(aData.x,uTime+0.0001)*isolation*(1.0+hover);
    vColor=nebulaLight(aData.w);
    vUv=uv;
  }
