// Generated by touchdesigner/cinematic/generate-field.mjs; source 7d910ec4a1499100.
// Native GLSL 4.30; exact source geometry/time with layered HDR optics.
layout(location=0) out vec4 fragBackground;
layout(location=1) out vec4 fragForeground;
uniform sampler2D sCoreDepth;
uniform vec4 uCameraPos, uCameraForward, uCameraInfo, uViewport;
uniform vec4 uFieldLook; // dust, recorded gas, filaments, decorative stars
in float vViewDepth;

float fieldDistanceAt(float normalizedDepth) {
  float n=uCameraInfo.z, f=uCameraInfo.w;
  return n*f/max(f-normalizedDepth*(f-n),0.000001);
}
void writeField(vec4 radiance, float gain) {
  vec2 uv=gl_FragCoord.xy*uViewport.zw;
  // Normalized depth must not interpolate a valid surface with far/no-hit=1.
  // Enforce nearest sampling even if the MAT's sampler filter is changed.
  ivec2 size=textureSize(sCoreDepth,0);
  ivec2 texel=clamp(ivec2(floor(uv*vec2(size))),ivec2(0),size-ivec2(1));
  float rawDepth=texelFetch(sCoreDepth,texel,0).r;
  float centerDepth=dot(-uCameraPos.xyz,uCameraForward.xyz);
  float coreDepth=(rawDepth>=0.0 && rawDepth<0.999999)
    ? fieldDistanceAt(rawDepth) : centerDepth;
  // Every fragment contributes continuously to both additive layers. No
  // sparse nearest-star depth may promote an entire accumulated field pixel.
  float band=0.065;
  float foreground=1.0-smoothstep(coreDepth-band,coreDepth+band,vViewDepth);
  vec3 color=max(radiance.rgb,vec3(0.0))*max(gain,0.0);
  float alpha=max(radiance.a,0.0);
  // RGB is straight here. Both MRTs MUST blend Source Alpha + One, with
  // postmultalpha=False and Render TOP allowbufblending=True.
  fragBackground=TDOutputSwizzle(vec4(color,alpha*(1.0-foreground)));
  fragForeground=TDOutputSwizzle(vec4(color,alpha*foreground));
}
  uniform float uAnimation;
  uniform float uMotionCoherence;
  in vec2 vUv;
  in vec3 vColor;
  in float vAlpha;
  in vec3 vVolumePosition;
  in vec3 vVolumeRay;
  in float vFootprint;
  in vec2 vMotion;

  float cloudHash(vec3 p) {
    p=fract(p*vec3(0.1031,0.1030,0.0973));
    p+=dot(p,p.yxz+33.33);
    return fract((p.x+p.y)*p.z);
  }
  float cloudNoise(vec3 p) {
    vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);
    return mix(mix(mix(cloudHash(i),cloudHash(i+vec3(1,0,0)),f.x),
                   mix(cloudHash(i+vec3(0,1,0)),cloudHash(i+vec3(1,1,0)),f.x),f.y),
               mix(mix(cloudHash(i+vec3(0,0,1)),cloudHash(i+vec3(1,0,1)),f.x),
                   mix(cloudHash(i+vec3(0,1,1)),cloudHash(i+vec3(1,1,1)),f.x),f.y),f.z);
  }
  // Uneven knots and branching dust channels share a world-space field across
  // dust, gas and traces. Camera movement exposes the same structures.
  vec2 cloudStructure(vec3 p) {
    float radius=length(p.xy);
    vec3 warped=p*7.4+vec3(sin(p.y*9.0),sin(p.x*8.0),0.0)*0.42;
    float coarse=cloudNoise(warped);
    float medium=cloudNoise(warped*2.07+vec3(17.1,3.8,9.4));
    float ridge=abs(sin(radius*39.0+p.z*19.0+coarse*7.5+medium*1.9));
    float transmission=mix(0.10,1.0,smoothstep(0.06,0.43,ridge));
    float knots=smoothstep(0.24,0.81,coarse*0.65+medium*0.35);
    return vec2(knots,transmission);
  }

  void main() {
    if(vAlpha<0.00001) discard;
    vec2 q=vUv*2.0-1.0;
    float radius=dot(q,q);
    if(radius>1.0)discard;
    vec3 p=vVolumePosition;
    vec2 structure=cloudStructure(p);
    // Three samples through the footprint soften gas into a volume. The fine
    // field is revealed by approach rather than a screen-space noise overlay.
    vec3 drift=vec3(0.013,-0.008,0.004)*uAnimation*(0.08+vMotion.x*0.30);
    float fine=cloudNoise(p*69.0+drift);
    fine+=cloudNoise((p+vVolumeRay*vFootprint*0.16)*69.0+drift);
    fine+=cloudNoise((p-vVolumeRay*vFootprint*0.16)*69.0+drift);
    fine/=3.0;
    float curls=cloudNoise(p*(124.0+vMotion.y*48.0)-drift);
    float gas=smoothstep(0.23,0.77,fine*0.75+curls*0.25);
    gas=mix(gas,fine,uMotionCoherence*0.24);
    float envelope=exp(-radius*2.4)*(1.0-smoothstep(0.45,1.0,radius));
    float density=(0.07+structure.x*2.2)*structure.y*gas*envelope;
    vec3 lit=mix(vColor*0.40,vColor*1.55,smoothstep(0.35,0.75,fine));
    lit=mix(lit,vec3(0.58,0.69,0.72),smoothstep(0.71,0.94,structure.x)*0.28);
    writeField(vec4(lit,vAlpha*density*(1.9+vMotion.x*0.55)),uFieldLook.y);
  }
