// Generated by touchdesigner/cinematic/generate-field.mjs; source 6941ce1ea6a34675.
// Native GLSL 4.30; exact source geometry/time with layered HDR optics.
layout(location=0) out vec4 fragBackground;
layout(location=1) out vec4 fragForeground;
uniform sampler2D sCoreDepth;
uniform vec4 uCameraPos, uCameraForward, uCameraInfo, uViewport;
uniform vec4 uFieldLook; // dust, recorded gas, filaments, decorative stars
in float vViewDepth;

float fieldDistanceAt(float normalizedDepth) {
  float n=uCameraInfo.z, f=uCameraInfo.w;
  return n*f/max(f-normalizedDepth*(f-n),0.000001);
}
void writeField(vec4 radiance, float gain) {
  vec2 uv=gl_FragCoord.xy*uViewport.zw;
  // Normalized depth must not interpolate a valid surface with far/no-hit=1.
  // Enforce nearest sampling even if the MAT's sampler filter is changed.
  ivec2 size=textureSize(sCoreDepth,0);
  ivec2 texel=clamp(ivec2(floor(uv*vec2(size))),ivec2(0),size-ivec2(1));
  float rawDepth=texelFetch(sCoreDepth,texel,0).r;
  float centerDepth=dot(-uCameraPos.xyz,uCameraForward.xyz);
  float coreDepth=(rawDepth>=0.0 && rawDepth<0.999999)
    ? fieldDistanceAt(rawDepth) : centerDepth;
  // Every fragment contributes continuously to both additive layers. No
  // sparse nearest-star depth may promote an entire accumulated field pixel.
  float band=0.065;
  float foreground=1.0-smoothstep(coreDepth-band,coreDepth+band,vViewDepth);
  vec3 color=max(radiance.rgb,vec3(0.0))*max(gain,0.0);
  float alpha=max(radiance.a,0.0);
  // RGB is straight here. Both MRTs MUST blend Source Alpha + One, with
  // postmultalpha=False and Render TOP allowbufblending=True.
  fragBackground=TDOutputSwizzle(vec4(color,alpha*(1.0-foreground)));
  fragForeground=TDOutputSwizzle(vec4(color,alpha*foreground));
}

in vec2 vSpriteUv;


  uniform float uAtmosphere;
  in vec3 vColor;
  in float vAlpha;
  in float vNote;
  in float vRotation;
  in float vMotionSpeed;
  void main() {
    vec2 q = vSpriteUv*2.0-1.0;
    float c=cos(vRotation), s=sin(vRotation);
    q = mat2(c,s,-s,c)*q;
    q.y *= 1.0+vMotionSpeed*1.15;
    q.y *= mix(1.0, 1.65, uAtmosphere);
    float r2=dot(q,q);
    if(r2>1.0 || vAlpha<0.00001) discard;
    float envelope = exp(-r2*mix(5.5,3.5,uAtmosphere));
    envelope *= 1.0-smoothstep(0.60,1.0,r2);

    float core=exp(-r2*42.0)*(1.0-uAtmosphere);
    float star=exp(-abs(q.x)*55.0-abs(q.y)*5.0)+exp(-abs(q.x)*5.0-abs(q.y)*55.0);
    vec3 radiance=vColor*envelope;
    radiance+=vec3(0.68,0.85,1.0)*core*(0.3+vNote*1.5);
    radiance+=vec3(0.45,0.65,0.8)*star*vNote*0.08*(1.0-uAtmosphere);
    writeField(vec4(radiance, vAlpha),uFieldLook.x);
  }
