// Generated by touchdesigner/cinematic/generate-field.mjs; source 6941ce1ea6a34675.
// Native GLSL 4.30; exact source geometry/time with layered HDR optics.
// One perspective Camera COMP drives these and the Render TOP camera.
uniform vec4 uCameraPos, uCameraRight, uCameraUp, uCameraForward;
uniform vec4 uCameraInfo; // tan(vertical FOV/2), aspect, near, far
uniform vec4 uViewport;   // physical width, height, inverse width, inverse height
vec3 tdWorldToView(vec3 p) {
  vec3 q=p-uCameraPos.xyz;
  return vec3(dot(q,uCameraRight.xyz),dot(q,uCameraUp.xyz),-dot(q,uCameraForward.xyz));
}
vec3 tdViewToWorld(vec3 p) {
  return uCameraPos.xyz+uCameraRight.xyz*p.x+uCameraUp.xyz*p.y-uCameraForward.xyz*p.z;
}
mat3 tdViewBasis() {
  return transpose(mat3(uCameraRight.xyz,uCameraUp.xyz,-uCameraForward.xyz));
}
// OpenGL [-1,1] clip Z is used only to encode a portable near=0/far=1
// color-depth texture; MAT rasterization always uses TDWorldToProj().
vec4 tdPerspectiveClip(vec3 world) {
  vec3 p=tdWorldToView(world);
  float n=uCameraInfo.z,f=uCameraInfo.w,t=uCameraInfo.x;
  return vec4(p.x/(t*uCameraInfo.y),p.y/t,
    -(f+n)/(f-n)*p.z-2.0*f*n/(f-n),-p.z);
}

uniform sampler2D sPositions;
uniform sampler2D sData;
uniform sampler2D sSizes;
uniform sampler2D sMotion;
uniform float uCount;
vec4 instanceTexel(sampler2D image,int index) {
  int width=textureSize(image,0).x;
  return texelFetch(image,ivec2(index%width,index/width),0);
}

out vec2 vSpriteUv;



  uniform float uPointScale;
  uniform float uPointMax;
  uniform float uSelLane;
  uniform float uSolo;
  uniform float uHoverLane;
  uniform float uReplaying;
  uniform float uAtmosphere;
  out vec3 vColor;
  out float vAlpha;
  out float vNote;
  out float vRotation;
  out float vMotionSpeed;

  uniform float uTime;
  uniform float uDuration;
  uniform float uOrbit;
  uniform float uTilt;
  vec3 nebulaTransform(vec3 p) {
    float angle = uOrbit + 3.45575191895 * uTime / max(uDuration, 1.0);
    float c = cos(angle), s = sin(angle);
    p.xy = mat2(c, s, -s, c) * p.xy;
    float inclination = 0.6981317008 + uTilt;
    c = cos(inclination); s = sin(inclination);
    p.yz = mat2(c, s, -s, c) * p.yz;
    c = 0.9689124217; s = -0.2474039593;
    p.xy = mat2(c, s, -s, c) * p.xy;
    return p;
  }
  vec3 nebulaLight(float heat) {
    vec3 cold = vec3(0.115, 0.39, 0.64);
    vec3 ice = vec3(0.47, 0.72, 0.86);
    vec3 amber = vec3(1.0, 0.39, 0.105);
    float warmth=smoothstep(0.63,0.9,heat);
    return mix(mix(cold,ice,smoothstep(0.18,0.63,heat)),amber,warmth)*(1.0+warmth*0.25);
  }


float nebulaPixelScale(vec3 viewPosition) {
  return 0.5*uViewport.y/uCameraInfo.x/max(0.0001,-viewPosition.z);
}


  float cloudHash(vec3 p) {
    p=fract(p*vec3(0.1031,0.1030,0.0973));
    p+=dot(p,p.yxz+33.33);
    return fract((p.x+p.y)*p.z);
  }
  float cloudNoise(vec3 p) {
    vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);
    return mix(mix(mix(cloudHash(i),cloudHash(i+vec3(1,0,0)),f.x),
                   mix(cloudHash(i+vec3(0,1,0)),cloudHash(i+vec3(1,1,0)),f.x),f.y),
               mix(mix(cloudHash(i+vec3(0,0,1)),cloudHash(i+vec3(1,0,1)),f.x),
                   mix(cloudHash(i+vec3(0,1,1)),cloudHash(i+vec3(1,1,1)),f.x),f.y),f.z);
  }
  // Uneven knots and branching dust channels share a world-space field across
  // dust, gas and traces. Camera movement exposes the same structures.
  vec2 cloudStructure(vec3 p) {
    float radius=length(p.xy);
    vec3 warped=p*7.4+vec3(sin(p.y*9.0),sin(p.x*8.0),0.0)*0.42;
    float coarse=cloudNoise(warped);
    float medium=cloudNoise(warped*2.07+vec3(17.1,3.8,9.4));
    float ridge=abs(sin(radius*39.0+p.z*19.0+coarse*7.5+medium*1.9));
    float transmission=mix(0.10,1.0,smoothstep(0.06,0.43,ridge));
    float knots=smoothstep(0.24,0.81,coarse*0.65+medium*0.35);
    return vec2(knots,transmission);
  }

  out float vViewDepth;

uniform vec4 uLensOptics; // focus distance, aperture 0..1, lens strength, reserved
float fieldDefocusDiameter(float depth) {
  float focus=max(uLensOptics.x,0.15);
  float nearWeight=1.0-smoothstep(focus*0.95,focus*1.05,depth);
  // A bounded circular projection PSF. World/source positions stay exact.
  // Scale the footprint with output height so lens character is consistent.
  float diameter=9.0*clamp(uLensOptics.y,0.0,1.0)
    *abs(depth-focus)/max(depth,0.15)*uViewport.y/720.0;
  return min(diameter,18.0*uViewport.y/720.0)*nearWeight;
}

void main() {
    int id=TDInstanceID();
    if(id>=int(uCount)) { gl_Position=vec4(2.0,2.0,2.0,1.0);return; }
    vec3 position=instanceTexel(sPositions,id).xyz;
vec4 aData=instanceTexel(sData,id);
vec2 aSize=instanceTexel(sSizes,id).xy;
vec4 aMotion=instanceTexel(sMotion,id);
    vec3 p = nebulaTransform(position);
    vec4 viewPosition=vec4(tdWorldToView(p),1.0);
    vSpriteUv=vec2(P.x+0.5,0.5-P.y);
    float focus = 1.0-step(0.5, abs(aData.y-uSelLane));
    float hover = (1.0-step(0.5, abs(aData.y-uHoverLane)))*0.5;
    float isolation = uSelLane < -0.5 ? 1.0 : mix(uSolo > 0.5 ? 0.0 : 0.12, 2.3, focus);
    float recent = exp(-max(0.0, uTime-aData.x)/550.0)*uReplaying;
    float diameter = aSize.x*nebulaPixelScale(viewPosition.xyz)*(1.0+focus*0.2+hover*0.15+aMotion.x*0.30);
    float sharpSize = clamp(diameter, 1.5, uPointMax);
    float coc=fieldDefocusDiameter(-viewPosition.z);
    float rasterSize=sqrt(sharpSize*sharpSize+coc*coc);
    viewPosition.xy+=P.xy*rasterSize/max(nebulaPixelScale(viewPosition.xyz),0.0001);
    vViewDepth=-viewPosition.z;
    gl_Position=TDWorldToProj(vec4(tdViewToWorld(viewPosition.xyz),1.0));
    float coverage = min(1.0, diameter*diameter/(sharpSize*sharpSize))
      *(sharpSize*sharpSize)/(rasterSize*rasterSize);
    float visible = step(aData.x, uTime+0.0001);
    float depthLight = 0.67+0.55*smoothstep(-0.6, 0.6, p.z);
    vec2 cloud=cloudStructure(position);
    vAlpha = aSize.y*visible*isolation*coverage*depthLight*(1.0+recent*0.85+hover+aMotion.x*0.42);
    vAlpha *= (0.28+cloud.x*1.45)*cloud.y;
    vColor = nebulaLight(aData.w);
    vColor = mix(vColor, vec3(0.9, 0.95, 1.0), aData.z*0.5);
    vNote = aData.z;
    vec3 radial=normalize(vec3(position.xy,0.0));
    vec3 direction=vec3(-radial.y,radial.x,0.0)*aMotion.z+radial*aMotion.w;
    vec3 viewDirection=tdViewBasis()*nebulaTransform(direction);
    vRotation = length(viewDirection.xy)>0.000001 ? atan(viewDirection.y,viewDirection.x) : 0.0;
    vMotionSpeed=aMotion.x;
  }
