// Generated by touchdesigner/cinematic/generate-field.mjs; source 866085645f9eeb5a.
// Native GLSL 4.30; exact source geometry/time with layered HDR optics.
layout(location=0) out vec4 fragBackground;
layout(location=1) out vec4 fragForeground;
uniform sampler2D sCoreDepth;
uniform vec4 uCameraPos, uCameraForward, uCameraInfo, uViewport;
uniform vec4 uFieldLook; // dust, recorded gas, filaments, decorative stars
in float vViewDepth;

float fieldDistanceAt(float normalizedDepth) {
  float n=uCameraInfo.z, f=uCameraInfo.w;
  return n*f/max(f-normalizedDepth*(f-n),0.000001);
}
void writeField(vec4 radiance, float gain) {
  vec2 uv=gl_FragCoord.xy*uViewport.zw;
  // Normalized depth must not interpolate a valid surface with far/no-hit=1.
  // Enforce nearest sampling even if the MAT's sampler filter is changed.
  ivec2 size=textureSize(sCoreDepth,0);
  ivec2 texel=clamp(ivec2(floor(uv*vec2(size))),ivec2(0),size-ivec2(1));
  float rawDepth=texelFetch(sCoreDepth,texel,0).r;
  float centerDepth=dot(-uCameraPos.xyz,uCameraForward.xyz);
  float coreDepth=(rawDepth>=0.0 && rawDepth<0.999999)
    ? fieldDistanceAt(rawDepth) : centerDepth;
  // Every fragment contributes continuously to both additive layers. No
  // sparse nearest-star depth may promote an entire accumulated field pixel.
  float band=0.065;
  float foreground=1.0-smoothstep(coreDepth-band,coreDepth+band,vViewDepth);
  vec3 color=max(radiance.rgb,vec3(0.0))*max(gain,0.0);
  float alpha=max(radiance.a,0.0);
  // RGB is straight here. Both MRTs MUST blend Source Alpha + One, with
  // postmultalpha=False and Render TOP allowbufblending=True.
  fragBackground=TDOutputSwizzle(vec4(color,alpha*(1.0-foreground)));
  fragForeground=TDOutputSwizzle(vec4(color,alpha*foreground));
}

in vec2 vSpriteUv;
  in vec3 vColor;
  in float vEnergy;
  void main() {
    vec2 p=vSpriteUv*2.0-1.0;
    float r2=dot(p,p);
    if(r2>1.0)discard;
    float profile=exp(-r2*6.0)*(1.0-smoothstep(0.65,1.0,r2));

    writeField(vec4(vColor,profile*vEnergy),uFieldLook.w);
  }
