// Generated by touchdesigner/generate-shaders.mjs; source 5c18f75419608234.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
layout(location=0) out vec4 fragColor;
#define vUv vUV.st

     #define uImage sTD2DInputs[0]
uniform vec4 uBlurStep;
#define uStep uBlurStep.xy
    void main() {
      vec3 c = texture(uImage, vUv).rgb * 0.227027;
      c += texture(uImage, vUv + uStep * 1.384615).rgb * 0.316216;
      c += texture(uImage, vUv - uStep * 1.384615).rgb * 0.316216;
      c += texture(uImage, vUv + uStep * 3.230769).rgb * 0.070270;
      c += texture(uImage, vUv - uStep * 3.230769).rgb * 0.070270;
      fragColor=TDOutputSwizzle(vec4(c, 1.0));
    }
