// Generated by touchdesigner/generate-shaders.mjs; source a94e05e5ecacbfa2.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
layout(location=0) out vec4 fragColor;
#define vUv vUV.st

     #define uImage sTD2DInputs[0]
    void main() {
      vec3 c = texture(uImage, vUv).rgb;
      float peak = max(c.r, max(c.g, c.b));
      fragColor=TDOutputSwizzle(vec4(c * smoothstep(0.38, 1.4, peak) * 0.5, 1.0));
    }
