// Generated by touchdesigner/generate-shaders.mjs; source 5b7555f1b655b4c2.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
layout(location=0) out vec4 fragColor;


  uniform float uDepthPass;
  in vec2 vUv;
  in float vSeed;
  float hash(vec2 p) { return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453); }
  float noise(vec2 p) {
    vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);
    return mix(mix(hash(i),hash(i+vec2(1.0,0.0)),f.x),mix(hash(i+vec2(0.0,1.0)),hash(i+1.0),f.x),f.y);
  }
  void main() {
    if(uDepthPass>0.5)discard;
    vec2 p=vUv*2.0-1.0;
    float envelope=exp(-dot(p,p)*4.0)*(1.0-smoothstep(0.55,1.0,length(p)));
    float cloud=noise(p*4.0+vSeed)*0.65+noise(p*11.0-vSeed)*0.35;
    fragColor=TDOutputSwizzle(vec4(vec3(0.07,0.15,0.27),envelope*cloud*0.023));
  }
