// Generated by touchdesigner/generate-shaders.mjs; source a98ddd38eea5c772.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
// One perspective Camera COMP drives these and the Render TOP camera.
uniform vec4 uCameraPos, uCameraRight, uCameraUp, uCameraForward;
uniform vec4 uCameraInfo; // tan(vertical FOV/2), aspect, near, far
uniform vec4 uViewport;   // physical width, height, inverse width, inverse height
vec3 tdWorldToView(vec3 p) {
  vec3 q=p-uCameraPos.xyz;
  return vec3(dot(q,uCameraRight.xyz),dot(q,uCameraUp.xyz),-dot(q,uCameraForward.xyz));
}
vec3 tdViewToWorld(vec3 p) {
  return uCameraPos.xyz+uCameraRight.xyz*p.x+uCameraUp.xyz*p.y-uCameraForward.xyz*p.z;
}
mat3 tdViewBasis() {
  return transpose(mat3(uCameraRight.xyz,uCameraUp.xyz,-uCameraForward.xyz));
}
// OpenGL [-1,1] clip Z is used only to encode a portable near=0/far=1
// color-depth texture; MAT rasterization always uses TDWorldToProj().
vec4 tdPerspectiveClip(vec3 world) {
  vec3 p=tdWorldToView(world);
  float n=uCameraInfo.z,f=uCameraInfo.w,t=uCameraInfo.x;
  return vec4(p.x/(t*uCameraInfo.y),p.y/t,
    -(f+n)/(f-n)*p.z-2.0*f*n/(f-n),-p.z);
}


float depthTexel(sampler2D image,vec2 uv) {
  ivec2 size=textureSize(image,0);
  ivec2 coord=clamp(ivec2(floor(uv*vec2(size))),ivec2(0),size-ivec2(1));
  return texelFetch(image,coord,0).r;
}
layout(location=0) out vec4 fragColor;
#define vUv vUV.st


    #define uField sTD2DInputs[0]
#define uDepth sTD2DInputs[1]
#define uCore sTD2DInputs[2]
#define uCoreDepth sTD2DInputs[3]


    float distanceAt(float d) { return uCameraInfo.z*uCameraInfo.w/(uCameraInfo.w-d*(uCameraInfo.w-uCameraInfo.z)); }
    float inside(vec2 p) { return step(0.0,p.x)*step(p.x,1.0)*step(0.0,p.y)*step(p.y,1.0); }
    void main() {
      vec3 coreView=tdWorldToView(vec3(0.0));
      float uDistance=-coreView.z,uAspect=uCameraInfo.y;
      float uEnabled=uDistance>0.20500000?1.0:0.0;
      vec2 uCenter=vec2(0.5);
      float uRadius=0.0;
      if(uEnabled>0.5) {
        uCenter+=coreView.xy/vec2(uCameraInfo.x*uAspect,uCameraInfo.x)/uDistance*0.5;
        uRadius=0.5*0.20500000/uCameraInfo.x/sqrt(max(0.00000001,uDistance*uDistance-0.042025000000));
      }
      vec2 delta=(vUv-uCenter)*vec2(uAspect,1.0);
      float radius=length(delta), r=max(uRadius,0.000001);
      float falloff=1.0-smoothstep(3.0*r,7.0*r,radius);
      float bend=min(1.65*r,1.5*r*r/max(radius,.65*r))*falloff*uEnabled;
      vec2 warped=vUv-delta/max(radius,0.000001)*bend/vec2(uAspect,1.0);
      float foreground=1.0-step(uDistance,distanceAt(depthTexel(uDepth,vUv)));
      vec2 source=mix(warped,vUv,foreground);
      // Do not duplicate an unrelated foreground star into a background arc.
      if(distanceAt(depthTexel(uDepth,source))<uDistance) source=vUv;
      vec3 background=texture(uField,source).rgb*inside(source);
      float sourceDistance=distanceAt(depthTexel(uDepth,source));
      vec4 nucleus=texture(uCore,vUv);
      float coreRawDepth=depthTexel(uCoreDepth,vUv);
      float coreDistance=coreRawDepth>.999999 ? uDistance : distanceAt(coreRawDepth);
      float front=1.0-step(coreDistance,sourceDistance);
      vec3 color=mix(background*(1.0-clamp(nucleus.a,0.0,1.0))+nucleus.rgb,
        background+nucleus.rgb*.12,front);
      fragColor=TDOutputSwizzle(vec4(color,1.0));
    }
