// Generated by touchdesigner/generate-shaders.mjs; source 1e31b808174b50c9.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
layout(location=0) out vec4 fragColor;
in vec2 vSpriteUv;


  uniform float uAtmosphere;
  uniform float uDepthPass;
  in vec3 vColor;
  in float vAlpha;
  in float vNote;
  in float vRotation;
  in float vMotionSpeed;
  void main() {
    vec2 q = vSpriteUv*2.0-1.0;
    float c=cos(vRotation), s=sin(vRotation);
    q = mat2(c,s,-s,c)*q;
    q.y *= 1.0+vMotionSpeed*1.15;
    q.y *= mix(1.0, 1.65, uAtmosphere);
    float r2=dot(q,q);
    if(r2>1.0 || vAlpha<0.00001) discard;
    float envelope = exp(-r2*mix(5.5,3.5,uAtmosphere));
    envelope *= 1.0-smoothstep(0.60,1.0,r2);
    if(uDepthPass>0.5) {
      if(uAtmosphere>0.5 || r2>0.16 || vAlpha*envelope<0.03) discard;
      fragColor=TDOutputSwizzle(vec4(vec3(gl_FragCoord.z),1.0)); return;
    }
    float core=exp(-r2*42.0)*(1.0-uAtmosphere);
    float star=exp(-abs(q.x)*55.0-abs(q.y)*5.0)+exp(-abs(q.x)*5.0-abs(q.y)*55.0);
    vec3 radiance=vColor*envelope;
    radiance+=vec3(0.68,0.85,1.0)*core*(0.3+vNote*1.5);
    radiance+=vec3(0.45,0.65,0.8)*star*vNote*0.08*(1.0-uAtmosphere);
    fragColor=TDOutputSwizzle(vec4(radiance, vAlpha));
  }
