// Generated by touchdesigner/generate-shaders.mjs; source 675ebb200fdd287a.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
layout(location=0) out vec4 fragColor;


  uniform float uDepthPass;
  in vec3 vColor;
  in float vAlpha;
  in float vAcross;
  in float vCoverage;
  void main() {
    if(uDepthPass>0.5) {
      if(vAlpha<0.02 || abs(vAcross)>0.30) discard;
      fragColor=TDOutputSwizzle(vec4(vec3(gl_FragCoord.z),1.0)); return;
    }
    float aa=max(fwidth(vAcross)*0.5,0.0001);
    float coverage=1.0-smoothstep(1.0-aa,1.0+aa,abs(vAcross));
    fragColor=TDOutputSwizzle(vec4(vColor,coverage*vCoverage*vAlpha));
  }
