// Generated by touchdesigner/generate-shaders.mjs; source 17df8496c7c706d2.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
// One perspective Camera COMP drives these and the Render TOP camera.
uniform vec4 uCameraPos, uCameraRight, uCameraUp, uCameraForward;
uniform vec4 uCameraInfo; // tan(vertical FOV/2), aspect, near, far
uniform vec4 uViewport;   // physical width, height, inverse width, inverse height
vec3 tdWorldToView(vec3 p) {
  vec3 q=p-uCameraPos.xyz;
  return vec3(dot(q,uCameraRight.xyz),dot(q,uCameraUp.xyz),-dot(q,uCameraForward.xyz));
}
vec3 tdViewToWorld(vec3 p) {
  return uCameraPos.xyz+uCameraRight.xyz*p.x+uCameraUp.xyz*p.y-uCameraForward.xyz*p.z;
}
mat3 tdViewBasis() {
  return transpose(mat3(uCameraRight.xyz,uCameraUp.xyz,-uCameraForward.xyz));
}
// OpenGL [-1,1] clip Z is used only to encode a portable near=0/far=1
// color-depth texture; MAT rasterization always uses TDWorldToProj().
vec4 tdPerspectiveClip(vec3 world) {
  vec3 p=tdWorldToView(world);
  float n=uCameraInfo.z,f=uCameraInfo.w,t=uCameraInfo.x;
  return vec4(p.x/(t*uCameraInfo.y),p.y/t,
    -(f+n)/(f-n)*p.z-2.0*f*n/(f-n),-p.z);
}

uniform sampler2D sStarts;
uniform sampler2D sEnds;
uniform sampler2D sData;
uniform sampler2D sMotion;
uniform float uCount;
vec4 instanceTexel(sampler2D image,int index) {
  int width=textureSize(image,0).x;
  return texelFetch(image,ivec2(index%width,index/width),0);
}





  uniform float uPointScale;
  uniform float uSelLane;
  uniform float uHoverLane;
  out vec3 vColor;
  out float vAlpha;
  out float vAcross;
  out float vCoverage;

  uniform float uTime;
  uniform float uDuration;
  uniform float uOrbit;
  uniform float uTilt;
  vec3 nebulaTransform(vec3 p) {
    float angle = uOrbit + 3.45575191895 * uTime / max(uDuration, 1.0);
    float c = cos(angle), s = sin(angle);
    p.xy = mat2(c, s, -s, c) * p.xy;
    float inclination = 0.6981317008 + uTilt;
    c = cos(inclination); s = sin(inclination);
    p.yz = mat2(c, s, -s, c) * p.yz;
    c = 0.9689124217; s = -0.2474039593;
    p.xy = mat2(c, s, -s, c) * p.xy;
    return p;
  }
  vec3 nebulaLight(float heat) {
    vec3 cold = vec3(0.115, 0.39, 0.64);
    vec3 ice = vec3(0.47, 0.72, 0.86);
    vec3 amber = vec3(1.0, 0.39, 0.105);
    float warmth=smoothstep(0.63,0.9,heat);
    return mix(mix(cold,ice,smoothstep(0.18,0.63,heat)),amber,warmth)*(1.0+warmth*0.25);
  }


float nebulaPixelScale(vec3 viewPosition) {
  return 0.5*uViewport.y/uCameraInfo.x/max(0.0001,-viewPosition.z);
}


  float cloudHash(vec3 p) {
    p=fract(p*vec3(0.1031,0.1030,0.0973));
    p+=dot(p,p.yxz+33.33);
    return fract((p.x+p.y)*p.z);
  }
  float cloudNoise(vec3 p) {
    vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);
    return mix(mix(mix(cloudHash(i),cloudHash(i+vec3(1,0,0)),f.x),
                   mix(cloudHash(i+vec3(0,1,0)),cloudHash(i+vec3(1,1,0)),f.x),f.y),
               mix(mix(cloudHash(i+vec3(0,0,1)),cloudHash(i+vec3(1,0,1)),f.x),
                   mix(cloudHash(i+vec3(0,1,1)),cloudHash(i+vec3(1,1,1)),f.x),f.y),f.z);
  }
  // Uneven knots and branching dust channels share a world-space field across
  // dust, gas and traces. Camera movement exposes the same structures.
  vec2 cloudStructure(vec3 p) {
    float radius=length(p.xy);
    vec3 warped=p*7.4+vec3(sin(p.y*9.0),sin(p.x*8.0),0.0)*0.42;
    float coarse=cloudNoise(warped);
    float medium=cloudNoise(warped*2.07+vec3(17.1,3.8,9.4));
    float ridge=abs(sin(radius*39.0+p.z*19.0+coarse*7.5+medium*1.9));
    float transmission=mix(0.10,1.0,smoothstep(0.06,0.43,ridge));
    float knots=smoothstep(0.24,0.81,coarse*0.65+medium*0.35);
    return vec2(knots,transmission);
  }

  void main() {
    int id=TDInstanceID();
    if(id>=int(uCount)) { gl_Position=vec4(2.0,2.0,2.0,1.0);return; }
    vec3 aStart=instanceTexel(sStarts,id).xyz;
vec3 aEnd=instanceTexel(sEnds,id).xyz;
vec4 aData=instanceTexel(sData,id);
vec4 aMotion=instanceTexel(sMotion,id);
vec3 position=vec3(P.x+0.5,P.y*2.0,0.0);
    vec3 start=tdWorldToView(nebulaTransform(aStart));
    vec3 end=tdWorldToView(nebulaTransform(aEnd));
    vec2 delta=end.xy-start.xy;
    vec2 perpendicular=vec2(-delta.y,delta.x)/max(length(delta),0.0000001);
    float width=(0.00055+aData.w*0.0008)*(1.0+aMotion.x*0.65);
    vec3 p=mix(start,end,position.x);
    float expanded=max(width,1.5/max(nebulaPixelScale(p),1.0));
    p.xy+=perpendicular*position.y*expanded;
    gl_Position=TDWorldToProj(vec4(tdViewToWorld(p),1.0));
    vAcross=position.y*2.0;
    vCoverage=width/expanded;
    float focus=1.0-step(0.5,abs(aData.y-uSelLane));
    float isolation=uSelLane < -0.5 ? 1.0 : mix(0.08,4.0,focus);
    float hover=1.0-step(0.5,abs(aData.y-uHoverLane));
    vColor=nebulaLight(aData.z);
    vec2 cloud=cloudStructure(mix(aStart,aEnd,position.x));
    vAlpha=step(aData.x,uTime+0.0001)*isolation*(0.022+aData.w*0.040)*(1.0+hover*0.5+aMotion.x*0.6);
    vAlpha *= (0.30+cloud.x*1.1)*cloud.y;
  }
