// Generated by touchdesigner/generate-shaders.mjs; source 2e5abe9a182803b9.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
layout(location=0) out vec4 fragColor;
#define vUv vUV.st

     #define uImage sTD2DInputs[0]
#define uGlow sTD2DInputs[1]
    vec3 toDisplay(vec3 c) {
      return mix(c * 12.92, 1.055 * pow(max(c, vec3(0.0)), vec3(1.0 / 2.4)) - 0.055,
        step(vec3(0.0031308), c));
    }
    void main() {
      vec3 linear = texture(uImage, vUv).rgb;
      vec3 light = linear + texture(uGlow, vUv).rgb * 0.21;
      vec3 c = vec3(1.0) - exp(-light * 1.18);
      c = toDisplay(c);
      float grain = fract(sin(dot(gl_FragCoord.xy, vec2(12.9898, 78.233))) * 43758.5453);
      c += (grain - 0.5) * 0.003;
      fragColor=TDOutputSwizzle(vec4(c, 1.0));
    }
