// Generated by touchdesigner/generate-shaders.mjs; source 92ea43fbe8f5a231.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
// One perspective Camera COMP drives these and the Render TOP camera.
uniform vec4 uCameraPos, uCameraRight, uCameraUp, uCameraForward;
uniform vec4 uCameraInfo; // tan(vertical FOV/2), aspect, near, far
uniform vec4 uViewport;   // physical width, height, inverse width, inverse height
vec3 tdWorldToView(vec3 p) {
  vec3 q=p-uCameraPos.xyz;
  return vec3(dot(q,uCameraRight.xyz),dot(q,uCameraUp.xyz),-dot(q,uCameraForward.xyz));
}
vec3 tdViewToWorld(vec3 p) {
  return uCameraPos.xyz+uCameraRight.xyz*p.x+uCameraUp.xyz*p.y-uCameraForward.xyz*p.z;
}
mat3 tdViewBasis() {
  return transpose(mat3(uCameraRight.xyz,uCameraUp.xyz,-uCameraForward.xyz));
}
// OpenGL [-1,1] clip Z is used only to encode a portable near=0/far=1
// color-depth texture; MAT rasterization always uses TDWorldToProj().
vec4 tdPerspectiveClip(vec3 world) {
  vec3 p=tdWorldToView(world);
  float n=uCameraInfo.z,f=uCameraInfo.w,t=uCameraInfo.x;
  return vec4(p.x/(t*uCameraInfo.y),p.y/t,
    -(f+n)/(f-n)*p.z-2.0*f*n/(f-n),-p.z);
}

uniform sampler2D sPositions;
uniform sampler2D sColors;
uniform sampler2D sSizes;
uniform float uCount;
vec4 instanceTexel(sampler2D image,int index) {
  int width=textureSize(image,0).x;
  return texelFetch(image,ivec2(index%width,index/width),0);
}



  out vec2 vSpriteUv;
  out vec3 vColor;
  out float vEnergy;
  void main() {
    int id=TDInstanceID();
    if(id>=int(uCount)){gl_Position=vec4(2.0,2.0,2.0,1.0);return;}
    vec3 position=instanceTexel(sPositions,id).xyz;
    vec3 aColor=instanceTexel(sColors,id).rgb;
    vec2 aSize=instanceTexel(sSizes,id).xy;
    vSpriteUv=vec2(P.x+0.5,0.5-P.y);
    vec4 view=vec4(tdWorldToView(position),1.0);

    float scale=0.5*uViewport.y/uCameraInfo.x;
    scale/=max(0.001,-view.z);
    float diameter=aSize.x*scale;
    float pointSize=clamp(diameter,1.2,8.0);
    view.xy+=P.xy*pointSize/scale;
    gl_Position=TDWorldToProj(vec4(tdViewToWorld(view.xyz),1.0));
    vEnergy=aSize.y*min(1.0,diameter*diameter/(pointSize*pointSize));
    vColor=aColor;
  }
