// Generated by touchdesigner/generate-shaders.mjs; source 98aef6e8597025c0.
// Native TouchDesigner 2023 GLSL 4.30+. Edit source, then regenerate.
layout(location=0) out vec4 fragColor;
in vec2 vSpriteUv;


  uniform float uDepthPass;
  in vec3 vColor;
  in float vEnergy;
  void main() {
    vec2 p=vSpriteUv*2.0-1.0;
    float r2=dot(p,p);
    if(r2>1.0)discard;
    float profile=exp(-r2*6.0)*(1.0-smoothstep(0.65,1.0,r2));
    if(uDepthPass>0.5) {
      if(r2>0.12 || vEnergy*profile<0.03)discard;
      fragColor=TDOutputSwizzle(vec4(vec3(gl_FragCoord.z),1.0)); return;
    }
    fragColor=TDOutputSwizzle(vec4(vColor,profile*vEnergy));
  }
